/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/articles': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List articles
         * @description Returns a paginated list of articles. Supports filtering by category, search term, and featured status.
         */
        get: operations['listArticles'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/articles/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get article details
         * @description Returns a single article by its ID or slug.
         */
        get: operations['getArticle'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/articles/trending': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get trending articles
         * @description Returns 4 randomly selected trending articles. Results change on every request. Use the exclude parameter to filter out articles already displayed.
         */
        get: operations['getTrendingArticles'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/categories': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all categories
         * @description Returns all article categories with their article counts.
         */
        get: operations['listCategories'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/breaking-news': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get breaking news
         * @description Returns a randomly selected breaking news item. May return a different item on each request.
         */
        get: operations['getBreakingNews'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/subscription': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get subscription status
         * @description Retrieves the current subscription status. Requires the `x-subscription-token` header.
         */
        get: operations['getSubscription'];
        put?: never;
        /**
         * Activate subscription
         * @description Activates the subscription (sets status to active). Requires the `x-subscription-token` header.
         */
        post: operations['subscribe'];
        /**
         * Deactivate subscription
         * @description Deactivates the subscription (sets status to inactive). Requires the `x-subscription-token` header.
         */
        delete: operations['unsubscribe'];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/subscription/create': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new subscription
         * @description Creates a new inactive subscription. The response includes the subscription token in the `x-subscription-token` response header. Store this token and include it in all subsequent subscription requests.
         */
        post: operations['createSubscription'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/publication/config': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get publication configuration
         * @description Returns publication configuration including enabled features, social links, and SEO defaults.
         */
        get: operations['getPublicationConfig'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/health': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the API and its dependent services (Redis).
         */
        get: operations['healthCheck'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Author: {
            /** @example Rhys Sullivan */
            name?: string;
            /** @example  */
            avatar?: string;
        };
        ContentBlock: {
            /** @enum {string} */
            type: 'paragraph';
            text: string;
        } | {
            /** @enum {string} */
            type: 'heading';
            /** @enum {integer} */
            level: 2 | 3;
            text: string;
        } | {
            /** @enum {string} */
            type: 'blockquote';
            text: string;
        } | {
            /** @enum {string} */
            type: 'unordered-list';
            items: string[];
        } | {
            /** @enum {string} */
            type: 'ordered-list';
            items: string[];
        } | {
            /** @enum {string} */
            type: 'image';
            /** Format: uri */
            src: string;
            alt: string;
            caption?: string;
        };
        Article: {
            /** @example 4eUawbAqhHBg0OzTSNeLwv */
            id?: string;
            /** @example Vercel Domains overhauled with instant search and at-cost pricing */
            title?: string;
            /** @example vercel-domains-overhauled-with-instant-search-and-at-cost-pricing */
            slug?: string;
            /** @example We've rebuilt Vercel Domains end to end, making it faster, simpler, and more affordable... */
            excerpt?: string;
            /** @description Structured content blocks. See the 'Rendering Article Content' section for details. */
            content?: components['schemas']['ContentBlock'][];
            /** @example changelog */
            category?: string;
            author?: components['schemas']['Author'];
            /**
             * Format: uri
             * @example https://i8qy5y6gxkdgdcv9.public.blob.vercel-storage.com/news/vercel-domains-overhauled-with-instant-search-and-at-cost-pricing.png
             */
            image?: string;
            /**
             * Format: date-time
             * @example 2026-01-15T09:00:00Z
             */
            publishedAt?: string;
            /**
             * @description Whether this article is featured on the homepage
             * @example true
             */
            featured?: boolean;
            /**
             * @example [
             *       "Vercel Domains"
             *     ]
             */
            tags?: string[];
        };
        BreakingNews: {
            /** @example breaking_001 */
            id?: string;
            /** @example Vercel Introduces the AI Cloud Platform */
            headline?: string;
            /** @example The same principles and ease of use you expect from Vercel, now for your agentic applications. */
            summary?: string;
            /** @example 3wYz2UxP8JRMZ9yNmvbFqv */
            articleId?: string;
            /** @example company-news */
            category?: string;
            /**
             * Format: date-time
             * @example 2026-01-26T09:00:00Z
             */
            publishedAt?: string;
            /** @example true */
            urgent?: boolean;
        };
        Subscription: {
            /** Format: uuid */
            token?: string;
            /**
             * @example active
             * @enum {string}
             */
            status?: 'active' | 'inactive';
            /**
             * Format: date-time
             * @example 2026-01-15T12:00:00Z
             */
            subscribedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Category: {
            /** @example changelog */
            slug?: string;
            /** @example Changelog */
            name?: string;
            /** @example 4 */
            articleCount?: number;
        };
        PaginationMeta: {
            /** @example 1 */
            page?: number;
            /** @example 20 */
            limit?: number;
            /** @example 18 */
            total?: number;
            /** @example 1 */
            totalPages?: number;
            /** @example false */
            hasNextPage?: boolean;
            /** @example false */
            hasPreviousPage?: boolean;
        };
        ArticleListResponse: {
            /** @example true */
            success?: boolean;
            data?: components['schemas']['Article'][];
            meta?: {
                pagination?: components['schemas']['PaginationMeta'];
            };
        };
        ArticleResponse: {
            /** @example true */
            success?: boolean;
            data?: components['schemas']['Article'];
        };
        CategoryListResponse: {
            /** @example true */
            success?: boolean;
            data?: components['schemas']['Category'][];
        };
        BreakingNewsResponse: {
            /** @example true */
            success?: boolean;
            data?: components['schemas']['BreakingNews'];
        };
        SubscriptionResponse: {
            /** @example true */
            success?: boolean;
            data?: components['schemas']['Subscription'];
        };
        ErrorResponse: {
            /** @example false */
            success?: boolean;
            error?: {
                /** @example NOT_FOUND */
                code?: string;
                /** @example Article with id 'xyz' not found */
                message?: string;
                /** @description Additional error details (validation errors, etc.) */
                details?: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listArticles: {
        parameters: {
            query?: {
                /** @description Page number (starts at 1) */
                page?: number;
                /** @description Items per page (max 100) */
                limit?: number;
                /** @description Filter by category slug */
                category?: 'changelog' | 'engineering' | 'customers' | 'company-news' | 'community';
                /** @description Search articles by title, excerpt, or tags */
                search?: string;
                /** @description Filter by featured status */
                featured?: 'true' | 'false';
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated article list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": [
                     *         {
                     *           "id": "4eUawbAqhHBg0OzTSNeLwv",
                     *           "title": "Vercel Domains overhauled with instant search and at-cost pricing",
                     *           "slug": "vercel-domains-overhauled-with-instant-search-and-at-cost-pricing",
                     *           "excerpt": "We've rebuilt Vercel Domains end to end, making it faster, simpler, and more affordable...",
                     *           "content": [
                     *             {
                     *               "type": "paragraph",
                     *               "text": "We've rebuilt Vercel Domains end to end, making it faster, simpler, and more affordable..."
                     *             }
                     *           ],
                     *           "category": "changelog",
                     *           "author": {
                     *             "name": "Rhys Sullivan",
                     *             "avatar": ""
                     *           },
                     *           "image": "https://i8qy5y6gxkdgdcv9.public.blob.vercel-storage.com/news/vercel-domains-overhauled-with-instant-search-and-at-cost-pricing.png",
                     *           "publishedAt": "2025-09-25T00:00:00.000-05:00",
                     *           "featured": false,
                     *           "tags": [
                     *             "Vercel Domains"
                     *           ]
                     *         }
                     *       ],
                     *       "meta": {
                     *         "pagination": {
                     *           "page": 1,
                     *           "limit": 20,
                     *           "total": 18,
                     *           "totalPages": 1,
                     *           "hasNextPage": false,
                     *           "hasPreviousPage": false
                     *         }
                     *       }
                     *     }
                     */
                    'application/json': components['schemas']['ArticleListResponse'];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
        };
    };
    getArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID (e.g. 4eUawbAqhHBg0OzTSNeLwv) or slug (e.g. building-secure-ai-agents) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ArticleResponse'];
                };
            };
            /** @description Article not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
        };
    };
    getTrendingArticles: {
        parameters: {
            query?: {
                /** @description Comma-separated list of article IDs to exclude (e.g. 4eUawbAqhHBg0OzTSNeLwv,6tdBZO7G0ySd5jrFwyw4Nq) */
                exclude?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Trending articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @example true */
                        success?: boolean;
                        data?: components['schemas']['Article'][];
                    };
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": [
                     *         {
                     *           "slug": "changelog",
                     *           "name": "Changelog",
                     *           "articleCount": 4
                     *         },
                     *         {
                     *           "slug": "engineering",
                     *           "name": "Engineering",
                     *           "articleCount": 3
                     *         },
                     *         {
                     *           "slug": "customers",
                     *           "name": "Customers",
                     *           "articleCount": 3
                     *         },
                     *         {
                     *           "slug": "company-news",
                     *           "name": "Company News",
                     *           "articleCount": 5
                     *         },
                     *         {
                     *           "slug": "community",
                     *           "name": "Community",
                     *           "articleCount": 3
                     *         }
                     *       ]
                     *     }
                     */
                    'application/json': components['schemas']['CategoryListResponse'];
                };
            };
        };
    };
    getBreakingNews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Breaking news item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "success": true,
                     *       "data": {
                     *         "id": "breaking_001",
                     *         "headline": "Vercel Introduces the AI Cloud Platform",
                     *         "summary": "The same principles and ease of use you expect from Vercel, now for your agentic applications.",
                     *         "articleId": "3wYz2UxP8JRMZ9yNmvbFqv",
                     *         "category": "company-news",
                     *         "publishedAt": "2025-07-10T09:00:00Z",
                     *         "urgent": true
                     *       }
                     *     }
                     */
                    'application/json': components['schemas']['BreakingNewsResponse'];
                };
            };
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header: {
                /** @description The subscription token received when creating a subscription */
                'x-subscription-token': string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['SubscriptionResponse'];
                };
            };
            /** @description Missing x-subscription-token header */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Subscription not found or expired */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header: {
                /** @description The subscription token received when creating a subscription */
                'x-subscription-token': string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription activated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['SubscriptionResponse'];
                };
            };
            /** @description Missing x-subscription-token header */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
        };
    };
    unsubscribe: {
        parameters: {
            query?: never;
            header: {
                /** @description The subscription token received when creating a subscription */
                'x-subscription-token': string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription deactivated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['SubscriptionResponse'];
                };
            };
            /** @description Missing x-subscription-token header */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
            /** @description Subscription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['ErrorResponse'];
                };
            };
        };
    };
    createSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New subscription created */
            201: {
                headers: {
                    /** @description The subscription token to use for subsequent operations */
                    'x-subscription-token'?: string;
                    [name: string]: unknown;
                };
                content: {
                    'application/json': components['schemas']['SubscriptionResponse'];
                };
            };
        };
    };
    getPublicationConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publication configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            /** @example Vercel Daily News */
                            publicationName?: string;
                            /** @example en */
                            language?: string;
                            /** @description Feature flags indicating which publication features are enabled. */
                            features?: {
                                /** @example true */
                                newsletter?: boolean;
                                /** @example true */
                                bookmarks?: boolean;
                                /** @example true */
                                comments?: boolean;
                                /** @example true */
                                darkMode?: boolean;
                                /** @example true */
                                searchSuggestions?: boolean;
                            };
                            socialLinks?: {
                                /**
                                 * Format: uri
                                 * @example https://twitter.com/vercel
                                 */
                                twitter?: string;
                                /**
                                 * Format: uri
                                 * @example https://github.com/vercel
                                 */
                                github?: string;
                                /**
                                 * Format: uri
                                 * @example https://discord.gg/vercel
                                 */
                                discord?: string;
                            };
                            seo?: {
                                /** @example Vercel Daily News */
                                defaultTitle?: string;
                                /** @example %s | Vercel Daily News */
                                titleTemplate?: string;
                                /** @example The latest news, tutorials, and insights for modern web developers. */
                                defaultDescription?: string;
                            };
                        };
                    };
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            /** @example ok */
                            status?: string;
                            /**
                             * Format: date-time
                             * @example 2026-01-15T12:00:00Z
                             */
                            timestamp?: string;
                            services?: {
                                /**
                                 * @example connected
                                 * @enum {string}
                                 */
                                redis?: 'connected' | 'error';
                            };
                        };
                    };
                };
            };
        };
    };
}
